language: node_js
node_js:
  - "8"
  - "9"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g hexo-cli
install:
- yarn
- yarn add hexo-deployer-git
script:
  - hexo clean
  - hexo generate
after_script:
- git init
- git config user.name "charlesmaxwellyoung"
- git config user.email "charlesmaxwellyoung@gmail.com"
- sed -i "s/gh_token/${access_token}/g" ./_config.yml
- hexo deploy
branches:
  only:
  - master